{{- if .Values.hazelcast.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hazelcast.fullname" . }}-configuration
  labels:
    app: {{ template "hazelcast.name" . }}
    chart: {{ template "hazelcast.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  hazelcast: |-
{{ toYaml .Values.hazelcast.configuration | indent 4 }}
{{- end -}}
