apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hazelcast
  labels:
    app: {{ template "hazelcast.name" . }}
    chart: {{ template "hazelcast.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ template "hazelcast.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: hazelcast-node
        image: {{ .Values.images.hazelcast.image }}
        ports:
        - containerPort: 5701
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
        env:
        - name: HZ_DATA
          value: /data/hazelcast
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration